In [2]:
import numpy as np

In [3]:
a =  np.arange(6).reshape(2, 3)
b =  np.arange(6,9).reshape(1, 3)

In [4]:
print(a)

[[0 1 2]
 [3 4 5]]


In [5]:
print(b)

[[6 7 8]]


In [6]:
shapes = [a.shape, b.shape]

m = a.flatten()
n = b.flatten()

c = np.array([*m, *n])

In [7]:
def inflate_matrixes(flat_thetas, shapes):
    layers  = len(shapes)+1
    sizes = [shape[0] * shape[1] for shape in shapes]
    steps = np.zeros(layers, dtype=int)

    for i in range(layers-1):
        steps[i+1] = steps[i] + sizes[i]
    return[
        flat_thetas[steps[i]: steps[i+1]].reshape(*shapes[i])
        for i in range(layers-1)
    ]


In [8]:
d = inflate_matrixes(c,shapes)
print(d)

[array([[0, 1, 2],
       [3, 4, 5]]), array([[6, 7, 8]])]
